server:
    port: 8080

spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password:

dyna-query:
    view-entity-package: com.jingweizhang
